### ISSUE TITLE
virt-query: not every disk has a source, and this leads to scary error messages

### ISSUE THREAD

**Issue by imz** [larsks/virt-utils#7]
I've been getting error messages like this (when calling
`virt-delete`, which call `virt-query disks`):

    # virt-query imz-puppet-master-ALT0-clone disks; echo $?
    file vda /var/lib/libvirt/images/imz-puppet-master0-clone.qcow2
    Traceback (most recent call last):
      File "/home/imz_mirror/virt-utils/virt-query", line 81, in <module>
        main()
      File "/home/imz_mirror/virt-utils/virt-query", line 72, in main
        for disk in dom.disks():
      File "/home/imz_mirror/virt-utils/virt-query", line 40, in disks
        'source': disk.find('source').get('file'),
    AttributeError: 'NoneType' object has no attribute 'get'
    1
    # 

I wondered what the reason can be. Here the code at line 40:

    def disks(self):
        for disk in self.domxml.xpath('/domain/devices/disk'):
            if disk.get('type') == 'file':
                info = {'type': 'file',
                        'source': disk.find('source').get('file'),
                        'target': disk.find('target').get('dev')}
                yield info

Well, not every such disk has a source! Consider my `virsh dumpxml imz-puppet-master-ALT0-clone`:

      <devices>
        <emulator>/usr/bin/qemu-kvm</emulator>
        <disk type='file' device='disk'>
          <driver name='qemu' type='qcow2'/>
          <source file='/var/lib/libvirt/images/imz-puppet-master0-clone.qcow2'/>
          <target dev='vda' bus='virtio'/>
          <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
        </disk>
        <disk type='file' device='cdrom'>
          <driver name='qemu' type='raw'/>
          <target dev='hda' bus='ide'/>
          <readonly/>
          <address type='drive' controller='0' bus='0' target='0' unit='0'/>
        </disk>

And a possible solution is: simply leave out this 3rd last field when
printing in such cases; luckily the source path is printed at the end
of the output lines!

From `virt-query`, line 72:

        for disk in dom.disks():
            print '{type} {target} {source}'.format(**disk)

**Comment by imz** [comment]
You have lost your commits with the two last merges in your current master branch. The lost commits: https://github.com/imz/virt-utils/commits/upstream
